services:
  # ---------------------------------------------
  # Базы данных и брокеры
  # ---------------------------------------------
  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pus_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pus_pass}
      POSTGRES_DB: ${POSTGRES_DB:-pus_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pus_user} -d ${POSTGRES_DB:-pus_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pus_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "15672:15672" # Management UI для удобного дебага
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pus_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pus_network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-password123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - pus_network

  minio-init:
    image: minio/mc:latest
    container_name: minio_init
    depends_on:
      - minio
    networks:
      - pus_network
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set myminio http://minio:9000 $${MINIO_USER:-admin} $${MINIO_PASSWORD:-password123};
      mc mb myminio/$${MINIO_DEFAULT_BUCKET:-reports} || true;
      mc anonymous set public myminio/$${MINIO_DEFAULT_BUCKET:-reports} || true;
      exit 0;
      "

  # ---------------------------------------------
  # Backend-сервисы
  # ---------------------------------------------
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: api
    restart: unless-stopped
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    command: bash ./backend/start.sh
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-pus_user}:${POSTGRES_PASSWORD:-pus_pass}@db:5432/${POSTGRES_DB:-pus_db}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
    networks:
      - pus_network

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: worker
    restart: unless-stopped
    working_dir: /app/backend
    command: faststream run app.broker.config:stream_app --reload
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-pus_user}:${POSTGRES_PASSWORD:-pus_pass}@db:5432/${POSTGRES_DB:-pus_db}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      api:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully
    networks:
      - pus_network

  # ---------------------------------------------
  # Web Server (Nginx)
  # ---------------------------------------------
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
    networks:
      - pus_network


  # ---------------------------------------------
  # Development
  # ---------------------------------------------
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - pus_network

networks:
  pus_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  minio_data:
